metadata:
  name: hardhat-network
spec:
  template:
    metadata:
      labels:
        app: hardhat-network
    spec:
      volumes:
        - name: hh-configmap-volume
          volumesource:
            configmap:
              localobjectreference:
                name: hardhat-config-map
      containers:
      - name: hardhat-network
        image: smartcontract/hardhat-network
        volumemounts:
          - name: hh-configmap-volume
            mountpath: /usr/app/hardhat.config.js
            subpath: hardhat.config.js
        ports:
        - containerPort: {{ .Values.evm.rpcPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.evm.rpcPort }}
          periodSeconds: 2
