apiVersion: v1
kind: ConfigMap
metadata:
  name: hardhat-config-map
objectmeta:
  name: hardhat-config-map
data:
  hardhat.config.js: |
    module.exports = {
        solidity: "0.7.3",
        networks: {
            hardhat: {
                chainId: 1337
            }
        }
    };