objectmeta:
  name: hardhat-network
spec:
  template:
    objectmeta:
      labels:
        app: hardhat-network
    spec:
      volumes:
        - name: hh-configmap-volume
          volumesource:
            configmap:
              localobjectreference:
                name: {{ .Values.evm.configMap }}
      containers:
      - name: hardhat-network
        image: smartcontract/hardhat-network
        volumemounts:
          - name: hh-configmap-volume
            mountpath: /usr/app/hardhat.config.js
            subpath: hardhat.config.js
        ports:
        - containerport: {{ .Values.evm.rpcPort }}
        readinessprobe:
          handler:
            exec: null
            httpget:
              path: /
              port:
                intval: {{ .Values.evm.rpcPort }}
          periodseconds: 2
