metadata:
  name: kafka-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod
  template:
    objectmeta:
      labels:
        app: kafka-pod
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.1.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: 2181
            - name: ZOOKEEPER_TICK_TIME
              value: 2000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1024m"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]
        - name: kafka-container
          image: confluentinc/cp-kafka:6.1.1
          env:
#            - name: KAFKA_ADVERTISED_PORT
#              value: 9092
#            - name: KAFKA_PORT
#              value: "9092"
#            - name: KAFKA_ADVERTISED_HOST_NAME
#              value: localhost
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: localhost:2181
            - name: KAFKA_BROKER_ID
              value: 1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 1
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 1
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 1
          ports:
            - containerPort: 9092
#            - containerPort: 29092
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"
#          readinessProbe:
#            tcpSocket:
#              port: 9092
#            initialDelaySeconds: 60
#            periodSeconds: 10
#          livenessProbe:
#            tcpSocket:
#              port: 9092
#            initialDelaySeconds: 60
#            periodSeconds: 10