
#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: zookeeper-deploy
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    objectmeta:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zoo
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1024m"
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 2181
#            initialDelaySeconds: 60
#            periodSeconds: 60
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 2181
#            initialDelaySeconds: 2
#            periodSeconds: 2