kind: Service
apiVersion: v1
metadata:
  name: node-registrar
  labels:
    app: node-registrar
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: node-registrar
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: node-registrar
    port: 80
    targetPort: 9898